server:
  port: 7003
spring:
  application:
    name: spring-cloud-eureka7003
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka7001.com:7001/eureka/,http://www.eureka7002.com:7002/eureka/
    register-with-eureka: false
    fetch-registry: false
