server:
  port: 8092
spring:
  application:
    name: spring-cloud-cusumer-hystrix

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://www.eureka7001.com:7001/eureka/,http://www.eureka7002.com:7002/eureka/,http://www.eureka7003.com:7003/eureka/ #eureka的服务地址

feign:
  hystrix:
    enabled: true

