server:
  port: 7002
spring:
  application:
    name: spring-cloud-eureka7002
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka7001.com:7001/eureka/,http://www.eureka7003.com:7003/eureka/
    register-with-eureka: false
    fetch-registry: false
